##############
# Config.yml #
##############

# Do not touch this parameter!
config-version: 2

# First Join #
# How much time online players have to welcome. (In seconds)
first-join:
  time-to-welcome: 30
  options:
    #Enable or Disable the ability to click on the message
    clickable-message: true
    #Enable or Disable the ability to see the “hover” message when you move your mouse over it.
    hover-message: true

# Spawn #
# If true new players will be teleported to this spawn.
spawn:
  enable: false
  location:
    world: "world"
    x: 0.0
    y: 50.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0
