name: Welcomer
version: '${project.version}'
main: fr.zekariateam.welcomer.Welcomer
api-version: 1.14
authors: [ Velris, Myoxyss ]
description: Plugin made to welcome players.
website: https://discord.gg/yDtMvtkk5F
commands:
  welcome:
    description: Commande pour souhaiter la bienvenue
    usage: /<command> [player]
    permission: welcomer.welcome
  welcomer:
    description: Commande de configuration du plugin
    permission: welcomer.config
    usage: /<command> spawn [set | enable | disable]